version: '3.0'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=axkxd
      - POSTGRES_PASSWORD=ksflsncGdsK
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - boost


networks:
  boost:
    driver: bridge
